/**
 * Stable error codes emitted by CaseFile refinements and validateAccusation.
 * Tests assert the SPECIFIC code (not bare success===false) to kill code-swap mutants.
 */
export enum CaseIssueCode {
  // R1 — uniqueness of catalog ids
  DUP_SUSPECT_ID = 'DUP_SUSPECT_ID',
  DUP_WEAPON_ID = 'DUP_WEAPON_ID',
  DUP_LOCATION_ID = 'DUP_LOCATION_ID',
  DUP_TIMESLOT_ID = 'DUP_TIMESLOT_ID',
  DUP_CLUE_ID = 'DUP_CLUE_ID',

  // R2 — exactly one culprit
  EXACTLY_ONE_CULPRIT = 'EXACTLY_ONE_CULPRIT',

  // R3 — isGuilty ⟺ role==='culprit'
  GUILT_ROLE_COHERENT = 'GUILT_ROLE_COHERENT',

  // R4 — victim id not reused as a suspect id
  VICTIM_NOT_SUSPECT = 'VICTIM_NOT_SUSPECT',

  // R5 — solution killer resolves and is the culprit
  KILLER_RESOLVES = 'KILLER_RESOLVES',
  KILLER_IS_CULPRIT = 'KILLER_IS_CULPRIT',

  // R6 — solution references resolve against catalogs
  SOLUTION_VICTIM_MATCHES = 'SOLUTION_VICTIM_MATCHES',
  SOLUTION_WEAPON_RESOLVES = 'SOLUTION_WEAPON_RESOLVES',
  SOLUTION_LOCATION_RESOLVES = 'SOLUTION_LOCATION_RESOLVES',
  SOLUTION_TIMESLOT_RESOLVES = 'SOLUTION_TIMESLOT_RESOLVES',

  // R7–R9 — three-tier knowledge semantics
  KNOWLEDGE_DISJOINT = 'KNOWLEDGE_DISJOINT',
  KNOWN_FACTS_SUBSET = 'KNOWN_FACTS_SUBSET',
  SECRET_FACT_COHERENT = 'SECRET_FACT_COHERENT',

  // R10 — relationship edges
  RELATIONSHIP_TARGET_RESOLVES = 'RELATIONSHIP_TARGET_RESOLVES',
  RELATIONSHIP_NO_SELF_EDGE = 'RELATIONSHIP_NO_SELF_EDGE',

  // R11–R12 — clue-presented trigger cross-checks
  SECRET_TRIGGER_RESOLVES = 'SECRET_TRIGGER_RESOLVES',
  ALIBI_TRIGGER_RESOLVES = 'ALIBI_TRIGGER_RESOLVES',

  // R13 — clue refersTo cross-checks
  CLUE_REFS_SUSPECT_RESOLVES = 'CLUE_REFS_SUSPECT_RESOLVES',
  CLUE_REFS_WEAPON_RESOLVES = 'CLUE_REFS_WEAPON_RESOLVES',
  CLUE_REFS_LOCATION_RESOLVES = 'CLUE_REFS_LOCATION_RESOLVES',
  CLUE_REFS_TIMESLOT_RESOLVES = 'CLUE_REFS_TIMESLOT_RESOLVES',

  // R14 — solvability: at least one non-culprit suspect
  WITNESS_OR_HERRING_PRESENT = 'WITNESS_OR_HERRING_PRESENT',

  // R15 — timeline order values unique
  TIMESLOT_ORDER_UNIQUE = 'TIMESLOT_ORDER_UNIQUE',

  // R16 — culprit alibi must be breakable
  CULPRIT_ALIBI_BREAKABLE = 'CULPRIT_ALIBI_BREAKABLE',

  // A1 — accusation well-formedness
  ACCUSATION_CASE_MISMATCH = 'ACCUSATION_CASE_MISMATCH',
  ACCUSED_NOT_SUSPECT = 'ACCUSED_NOT_SUSPECT',
  ACCUSED_WEAPON_RESOLVES = 'ACCUSED_WEAPON_RESOLVES',
  ACCUSED_LOCATION_RESOLVES = 'ACCUSED_LOCATION_RESOLVES',
  ACCUSED_TIMESLOT_RESOLVES = 'ACCUSED_TIMESLOT_RESOLVES',
}
